name: Flutter Web Deployment

on:
  push:
    branches: 
      - test-dev
      - test-uat
      - test-prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web --dart-define=ENV=qa 

      - name: Deploy to S3 (dev) #this step runs only push to the dev branch
        if: github.ref == 'refs/heads/test-dev' #Branch Header
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws s3 sync ./build/web s3://dev-saysomthing --delete 

      - name: Deploy to S3 (uat) #this step runs only push to the uat branch
        if: github.ref == 'refs/heads/test-uat' #Branch Header
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws s3 sync ./build/web s3://www.alliontesting.info --delete

      - name: Deploy to S3 (prod) #this step runs only push to the prod branch
        if: github.ref == 'refs/heads/test-prod' #Branch Header
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws s3 sync ./build/web s3://www.alliontesting.info --delete

      # - name: Invalidate CloudFront Cache
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set region us-east-1
      #     aws cloudfront create-invalidation --distribution-id "E2383CL3O3TLI8" --paths "/*"
